### ISSUE TITLE
Possible Issue Duplicating Ore Smelting

### ISSUE THREAD

**Issue by trismegistis** [DoubleDoorDevelopment/MineTweakerRecipeMaker#11]
Hi. I have a server, and, while I can't confirm this, after creating a MTRM recipe, vanilla ores seem to smelt large amounts of ingots. For instance, Iron Chunks (from fortune ores) smelt into 13 Iron ingots, with gold, it makes 7... Any ideas why?

**Comment by Claycorp** [comment]
"Vanilla ore"
"IronChunks (from fortune ores)"

Please explain how those relate at all.

**Comment by trismegistis** [comment]
Sorry, what I mean by vanilla ore is Iron and Gold. Osmium Ore blocks and Osmium Chunks from fortune ore don't do this, or any other mod ore whether fortune chunk or actual ore block. Sorry for the confusion. It seems when I restarted without MinetweakerRecipeMaker's recipes in the scripts folder anymore, the ore processing is the same. My MTRM script looks like this:

// File generated by MineTweakerRecipeMaker
//                     READ THIS HEADER BEFORE EDITING ANYTHING
// ================================================================================
//     This file is read and changed by the mod.
//     If you remove/edit any of the markers, IT WILL STOP WORKING!
//     If you want to make manual edits, make a backup of this file!
//     Markers look like this: "//#MARKER something"
//     They indicate where calls should be placed, so that MineTweaker does them in the correct order.
//     Removes come first, then stuff is added.
// ================================================================================
//

// ================================================================================
//#MARKER REMOVE
recipes.remove(<tinker_io:fuelInputMachine>);

// ================================================================================
//#MARKER REMOVE SHAPELESS
recipes.removeShapeless(<Calculator:RedstoneIngot> * 8, [<minecraft:redstone>, <ore:coal>]);
recipes.removeShapeless(<Calculator:RedstoneIngot> * 8, [<minecraft:redstone>, <ore:coal>]);
recipes.removeShapeless(<Calculator:RedstoneIngot> * 8, [<minecraft:redstone>, <ore:coal>]);
recipes.removeShapeless(<Calculator:RedstoneIngot> * 8, [<minecraft:redstone>, <ore:coal>]);

// ================================================================================
//#MARKER REMOVE SHAPED
recipes.removeShaped(<Calculator:RedstoneIngot> * 8, [[<minecraft:redstone>, <ore:coal>]]);
recipes.removeShaped(<Calculator:RedstoneIngot>, [[<ore:dustRedstone>]]);

// ================================================================================
//#MARKER ADD

// ================================================================================
//#MARKER ADD SHAPELESS
recipes.addShapeless(<minecraft:stick>, [<minecraft:planks:3>, <minecraft:planks:3>]);
recipes.addShapeless(<Calculator:RedstoneIngot> * 8, [<minecraft:redstone>, <ore:coal>]);
recipes.addShapeless(<Calculator:RedstoneIngot>, [<ore:dustRedstone>]);
recipes.addShapeless(<Calculator:RedstoneIngot>, [<ore:dustRedstone>]);
recipes.addShapeless(<Calculator:RedstoneIngot>, [<ore:dustRedstone>]);
recipes.addShapeless(<Calculator:RedstoneIngot>, [<ore:dustRedstone>]);
recipes.addShapeless(<Calculator:RedstoneIngot>, [<ore:dustRedstone>]);
recipes.addShapeless(<Calculator:RedstoneIngot>, [<ore:dustRedstone>]);
recipes.addShapeless(<Calculator:RedstoneIngot>, [<ore:dustRedstone>]);
recipes.addShapeless(<Calculator:RedstoneIngot>, [<ore:dustRedstone>]);
recipes.addShapeless(<Calculator:RedstoneIngot>, [<ore:dustRedstone>]);
recipes.addShapeless(<Calculator:RedstoneIngot>, [<ore:dustRedstone>]);
recipes.addShapeless(<Calculator:RedstoneIngot>, [<ore:dustRedstone>]);
recipes.addShapeless(<Calculator:RedstoneIngot>, [<ore:dustRedstone>]);
recipes.addShapeless(<Calculator:RedstoneIngot>, [<ore:dustRedstone>]);

// ================================================================================
//#MARKER ADD SHAPED
recipes.addShaped(<ExtraUtilities:curtains> * 12, [[<minecraft:wool>, null, <ore:blockWoolWhite>], [null, <ore:blockWoolWhite>, null], [<ore:blockWoolWhite>, null, <ore:blockWoolWhite>]]);
recipes.addShaped(<ExtraUtilities:curtains>, [[<ore:blockWoolWhite>, null, <ore:blockWoolWhite>], [null, <ore:blockWoolWhite>, null], [<ore:blockWoolWhite>, null, <ore:blockWoolWhite>]]);
recipes.addShaped(<Calculator:RedstoneIngot>, [[<ore:dustRedstone>]]);
recipes.addShaped(<minecraft:paper>, [[null, <ActuallyAdditions:itemFood:16>, null], [<ore:cropRice>, null, <ore:cropRice>], [null, <ore:cropRice>, null]]);
recipes.addShaped(<minecraft:paper>, [[null, <ActuallyAdditions:itemFood:16>, null], [<ore:cropRice>, null, <ore:cropRice>], [null, <ore:cropRice>, null]]);

**Comment by dries007** [comment]
First of all, you can remove all of the duplicate lines in there.
Secondly, `It seems when I restarted without MinetweakerRecipeMaker's recipes in the scripts folder anymore, the ore processing is the same` Do you mean that it remains screwed up when you remove the script? because if that is the case, its not MineTweaker (or rather, not this script, it could be some other script you have in there)
