### ISSUE TITLE
Recipies wont save 

### ISSUE THREAD

**Issue by madjam1231** [DoubleDoorDevelopment/MineTweakerRecipeMaker#12]
I make the recipe and when I try and press OK! nothing happens 
I am on ftb infintity

**Comment by dries007** [comment]
Screenshots and logs please

**Comment by madjam1231** [comment]
screenshots http://imgur.com/a/vvuEM

[fml-client-latest.txt](https://github.com/DoubleDoorDevelopment/MineTweakerRecipeMaker/files/34698/fml-client-latest.txt)
[latest.txt](https://github.com/DoubleDoorDevelopment/MineTweakerRecipeMaker/files/34699/latest.txt)

**Comment by dries007** [comment]
FTB infinity evolved seems to not allow custom recipe changes. Not an issue for us I'm afraid.
I'm looking into how to fix this, as its also preventing me from changing recipes on my server. If you find a way please post it.

**Comment by madjam1231** [comment]
ok one of the FTB people helped me on reddit heres the link https://www.reddit.com/r/feedthebeast/comments/3st3ff/minetweaker_recipe_maker_doesnt_work_for_me_with/
