### ISSUE TITLE
Avaritia Support please <3

### ISSUE THREAD

**Issue by AngelKairi** [DoubleDoorDevelopment/MineTweakerRecipeMaker#13]
It basically uses the same file, only for a different line like: http://pastebin.com/z3piWudB

Mod is found here: http://minecraft.curseforge.com/projects/avaritia?gameCategorySlug=mc-mods&projectID=233785

It relies on MT to work, so... should be fun?

**Comment by blockbreaker1361** [comment]
I would love to see Avaitia support from this mod as well. Avaritia can be a bit complicated to figure out.

**Comment by dries007** [comment]
The 1.9 / 1.10 version will be capable of supporting other crafting formats, but the old (1.7.10) version is too difficult to update to allow that. Sorry.
