### ISSUE TITLE
Crashes when trying to load scripts

### ISSUE THREAD

**Issue by jaredlll08** [DoubleDoorDevelopment/MineTweakerRecipeMaker#15]
Hey guys,
So a while ago, I implemented script sorting, since it has been on the TODO list for a while, and people wanted it, and it appears that it causes a crash with your sub-folder structure of "scripts\MineTweakerRecipeMaker\scripts\script-file".

The easiest way to fix this would be to generate your script files in the main script directory.
I figured I should let you guys know ahead of time so there isn't any miscommunication or misunderstandings

~Jared

**Comment by dries007** [comment]
KK

**Comment by dries007** [comment]
Quick question, while I'm doing this quick fix. Is the reload API still at `minetweaker.MineTweakerImplementationAPI.reload()` ? 
(Or is that gonna change in the near future, since we use reflection it won't crash, but It'd be nice to keep autoreloading working)

**Comment by jaredlll08** [comment]
uh, yea, still there, I don't plan on replacing package names, maybe come 1.11, but right now, package names won't change.

**Comment by dries007** [comment]
Ok, I thought that was the case, for compatibility's sake. 

Issue fixed by cc54c65
