### ISSUE TITLE
Cant join vanilla servers with your mod installed

### ISSUE THREAD

**Issue by Hax165** [DoubleDoorDevelopment/MineTweakerRecipeMaker#16]
Specifically SpongeForge Servers without mods. No errors are given, other than it wont let me connect unless i also have it installed on every server i want to join.

Using MineTweakerRecipeMaker-1.10.2-1.2.1.18
On Forge-1.10.2-12.18.2.2107
and spongeforge-1.10.2-2098-6.0.0-BETA-1823

**Comment by Claycorp** [comment]
Just turn it off? It was intentionally made like this so people don't think they can modify scripts anywhere they please. Its required on the server if you want to use it on the server but it should not be required on the client.
Plus I'm not sure why you would use a dev instance to connect to a server that isn't using whatever you are working on. This mod isn't an everyday use thing like JEI or WAILA.

**Comment by dries007** [comment]
Oops, Will be fixed next build.

**Comment by Hax165** [comment]
No worries, take your time ;)

**Comment by dries007** [comment]
It's fixed, i just forgot to close this issue. Build >= 19 (the most recent on curse has the fix)

**Comment by Hax165** [comment]
Alright thanks :D

**Comment by Hax165** [comment]
I still get a mod rejection which says "Mod restrictions [FMLMod:mtrm{1.2.1.19}]"

**Comment by dries007** [comment]
Will be looked into.

**Comment by Hax165** [comment]
Awesome ;)

**Comment by dries007** [comment]
Can you try build 20 from [here](https://jenkins.dries007.net/job/MineTweakerRecipeMaker/)?

**Comment by Hax165** [comment]
Sure ill give it a go

**Comment by Hax165** [comment]
Yep that fixed it, Thank you so muck 💃

**Comment by dries007** [comment]
I'll upload it to Curse
