### ISSUE TITLE
Doesnt work with spawn eggs

### ISSUE THREAD

**Issue by deividaslord** [DoubleDoorDevelopment/MineTweakerRecipeMaker#17]
![capture](https://cloud.githubusercontent.com/assets/24681210/21357121/5be940b0-c6d4-11e6-9c82-5a44842d3a44.PNG)
I tried to make a crafting recipe for a creeper, but apperently it doesnt work. :/ And now i cant remove the recipe aswell

**Comment by dries007** [comment]
Could you paste the relevant line of your MTRM script file?
I'm pretty sure you need to have both metadata and NBT tags enabled on the output item or it'll turn into a broken white egg.

**Comment by deividaslord** [comment]
![capture](https://cloud.githubusercontent.com/assets/24681210/21364755/6782944e-c6f2-11e6-9dc0-26170151874b.PNG)
did you speak about this? i cant choose any options in left, when spawnegg is selected

**Comment by dries007** [comment]
So according to the wiki, you need to specify the right NBT Tag. MTRM doesn't support NBT tags, but you can add this to the text box at the top, and it should work.
`.withTag({EntityTag:{id:"minecraft:creeper"}})`
For more info see http://minecraft.gamepedia.com/Spawn_Egg#Data_values & http://minetweaker3.powerofbytes.com/wiki/Tutorial:Advanced_Recipes

**Comment by deividaslord** [comment]
But i cant write in the box? So whats the config folder called then, cant find it. :(

**Comment by dries007** [comment]
I think you can only type in the textbox once it's showing the entire recipe line. I forget, its been a while.

Ok, you are gonna have to get a little more familiar with Minetweaker. I recommenced just quickly glossing over the wiki.

The script file is called '/scripts/MineTweakerRecipeMaker.zs/'. You can remove the wrong lines there and also add the tag manually.
