### ISSUE TITLE
Error with Aledged Duplicate entry

### ISSUE THREAD

**Issue by ranger135xp** [DoubleDoorDevelopment/MineTweakerRecipeMaker#18]
Hello,

I was trying to make a shapeless recipe for skeleton skulls to bone meal and I get an error that there's a "Duplicate Thermal Expansion Pulverizer Recipe found for ,EnderIO:blockEndermanSkull>, Command ignored!"

I do have a recipe for Enderman skulls in ModTweaker, but not one for the MC skeleton skull. Currently, the only thing that can turn this into bone meal is Factorization and that is by default. Any idea on this error? I appreciate your time.

![2016-12-25_00 58 39](https://cloud.githubusercontent.com/assets/15115164/21469923/e35cdd9c-ca3d-11e6-876a-97fd69234bab.png)

**Comment by Claycorp** [comment]
Not our mod blocking it. I'm not sure how ModTweaker deals with duplicate recipes. I assume its a config option you can turn on/off but I would say check the wiki to find more info.
