### ISSUE TITLE
added recipes not loading

### ISSUE THREAD

**Issue by SneakyDevil** [DoubleDoorDevelopment/MineTweakerRecipeMaker#19]
Running 1.7.10 and removed some recipes I had added a while back, but now whenever the game starts up or when /mt reload is done I get and error and all added recipes just won't load BUT they will get removed...
"ERROR: Error executing MineTweakerRecipeMaker: Index 0, Size: 0"

[scripts.zip](https://github.com/stanhebben/MineTweaker3/files/681918/scripts.zip)

**Comment by dries007** [comment]
I'm 99.9% sure this is a Minetweaker problem, but just in case its not, can you upload your entire log please?

**Comment by SneakyDevil** [comment]
According to one of the collab people on the minetweaker GitHub it isn't. They practically drop kicked me for even trying to ask for help.

Which log would have what you are looking for? My modpack generates quite a few.

**Comment by dries007** [comment]
Start with the minetweaker.log

**Comment by SneakyDevil** [comment]
http://puu.sh/ta7gK/0ebbc14b85.log

I didn't even know MT had its own log, it looks like MTRM is returning null on something but after it loads all the recipes...which don't show up.

**Comment by dries007** [comment]
The reason it's telling you its MineTweakerRecipeMaker, is because you put all of the scripts in a folder called `MineTweakerRecipeMaker`. Try moving them out, to the script folder. (Don't do the crafting one though, that'd the only one from MTRM)
"ERROR: scripts/ExtraTiC.zs:5: Could not resolve <liquid : liquidessence>"

**Comment by SneakyDevil** [comment]
*I* didn't do it, I've just been working on patching together an older modpack that's been dropped because *reasons*

Thanks for the help, I'll try that right now.

**Comment by dries007** [comment]
Oh, well, I assumed, but it doesn't really matter.

Np, feel free to comment if the issue persists.
