### ISSUE TITLE
No Permissions

### ISSUE THREAD

**Issue by felixletsplayYT** [DoubleDoorDevelopment/MineTweakerRecipeMaker#21]
When I have installed it and started using. 
It says me that I don't have the permission
I am OP Level 4

**Comment by dries007** [comment]
You have the mod on the client and one the server right?
Can you post a log from when you use the '/mtrm' command please?

**Comment by YOYOK9** [comment]
Hello I am having this same issue. I am on a sponge forge server using Luckyperms permissions manager.
Command ran at: [23:19:52]
Latest log: http://pastebin.com/TZqxGVAT     (from where i used the command) [file is too big]
=============
Sponge: 1.10.2-2221-5.1.0-BETA-2151
Forge: 1.10.2-12.18.3.2185
Luckyperms: Sponge-2.17.61
Mc: 1.10.2
mtrm: 1.10.2-1.2.1.20
Crafttweaker: 1.10.2-3.0.20

For mods like likyperms or pex is there a permission node for this mod?

**Comment by Claycorp** [comment]
There is no permission node as we don't support anything outside of Forge itself.

**Comment by YOYOK9** [comment]
How can I give myself perms to use it on the server? I can script well with minetweaker but this mod is useful for my admins to add or remove recipes.

**Comment by Claycorp** [comment]
Don't use permission systems and sponge? but seriously I have no clue. Something you are using is likely changing OP perm levels and thus breaking it. Nothing we can do about that.

**Comment by YOYOK9** [comment]
Could you not just add a permission node to allow plugins to tap into? ex: mtrm.gui.base or something? Just really like using this with servers.

**Comment by dries007** [comment]
**We cannot, without adding a hard dependency, add any permission API, unless its build into Forge.**

Your permission mod should have a mechanism for adding permission to vanilla/modded commands (or allow them based on the vanilla/forge build in mechanics). If it does not, you should not be using it with mods. Most have commands, and (almost) none add permissions nodes or other nonsense.
