### ISSUE TITLE
MTRM folder denying CraftTweaker from load

### ISSUE THREAD

**Issue by Eufranio** [DoubleDoorDevelopment/MineTweakerRecipeMaker#24]
When creating an script with MineTweakerRecipeMaker, it is stored in scripts/MineTweakerRecipeMaker/scripts/Crafting.zs file. When this folders/file are created, CraftTweaker will start throwing errors, look: https://github.com/jaredlll08/CraftTweaker/issues/99

If you can't fix I would like to just be able to choose the location of the Crafting.zs script. Looks like removing your folder from there the scripts will work.

**Comment by dries007** [comment]
This has been fixed already if I remember correctly, are you sure you are using the latest version?

**Comment by Eufranio** [comment]
Yes, I am, latest version for 1.7.10 tho. 

MineTweakerRecipeMaker-1.7.10-1.1.0.11
CraftTweaker-1.7.10-3.0.13

**Comment by dries007** [comment]
Ah I see now, the issue was fixed in the 1.8+ versions, but not in 1.7.10 because there was no error back then. I'm guessing Jared back-ported some code over or the underlying MT system changed. I'll make an updated build.

**Comment by Eufranio** [comment]
Backport the fix to 1.7? Thanks!

**Comment by dries007** [comment]
Can you try this build first please?
https://jenkins.dries007.net/job/MineTweakerRecipeMaker/15/artifact/build/libs/MineTweakerRecipeMaker-1.7.10-1.1.0.15.jar

2017-02-13 18:57 GMT+01:00 Eufranio <notifications@github.com>:

**Comment by dries007** [comment]
Somehow I forgot to upload that build to Curse, the issue was already fixed, but the build was never uploaded.

**Comment by Eufranio** [comment]
Still the same problem.

**Comment by dries007** [comment]
You updated the server too right?

**Comment by Eufranio** [comment]
Yes.

**Comment by dries007** [comment]
Hmm ok, then more research is needed.

**Comment by dries007** [comment]
I'm a derp, I had 1.10.2 sources in my 1.7.10 folder and I didn't check the version before thinking it was fixed already. A new port will be made and I'll look into the NEI think, but if it takes more then 10 minutes I can't do it today.

**Comment by dries007** [comment]
Fixed with new build, its been uploaded to CurseForge, so it'll take 15 minutes or so to get approved.
https://minecraft.curseforge.com/projects/minetweaker-recipemaker/files/2381332

**Comment by jaredlll08** [comment]
I didn't backport any code, last 1.7.10 version I did was 22nd of October, so no idea why this only appears now O_o

**Comment by Eufranio** [comment]
This appeared before, but I reported for you and you just said to create a new file.

**Comment by jaredlll08** [comment]
And that fix has worked for other people, so I'm not sure why it didn't work for you

**Comment by dries007** [comment]
I'm guessing that its just that noone has used Crafttweaker up till now (or none reported it).

This fix moves the old file to the a new one called "MineTweakerRecipeMaker" in the main scripts folder. (Just like the 1.10.2 fix, so nothing will be lost.)

**Comment by LukaPix** [comment]
This still happens if there is any more than the minetweakerrecipemaker script in "scripts" it doesn't matter if it's in another folder more than one file and it will just not work. I am currently just doing all my manual scripting in the minetweakerrecipemaker file but this is rather unorganized and not a desireable fix..

**Comment by Claycorp** [comment]
I've been using CT 3.0.13 with MTRM 1.1.1 for a few weeks now and there is no such issue with not allowing other files. You need to provide more information as currently it sounds like you are doing something wrong.

Also 1.7.10 is done, There will be no updates to it.

**Comment by LukaPix** [comment]
Sry im am a Derp i didn't use crafttweaker but minetweaker

**Comment by LukaPix** [comment]
I am using the same Versions.
Okay for example ProjectE creates a projecte_default.zs in .minecraft/scripts and there is the MTRM script in .minecraft/scripts/minetweakerrecipemaker/scripts/ if i delete one of the two after my game is started i can enter my world and everything works. If i don't it throws an error with something iterating through folders or files. It even throws this error if i create two empty .zs files in .minecraft/scripts. One file no problem, two files anywhere in the folder structure and it doesn't load. But this is probably a problem in CT not MTRM

**Comment by Claycorp** [comment]
There is no way you are using the same versions. MTRM 1.1.1 doesn't make a file in a folder anymore, That's what this whole issue you are replying to is about. Also CraftTweaker and MineTweaker has supported multiple .zs files in 1.7.10 forever.

What you are saying is happening is totally impossible. Delete the mods and get them from a proper source like CurseForge.

**Comment by LukaPix** [comment]
I downloaded them from curseforge. Im linking a log a soon as i can.
I know that, and i also used these exact versions in other 1.7.10 packs i made and never had a problem,
 but now its there.
