### ISSUE TITLE
NEI overriding visuals

### ISSUE THREAD

**Issue by Eufranio** [DoubleDoorDevelopment/MineTweakerRecipeMaker#25]
As you will make another 1.7 build I would like to let you know that NEI is overriding the visual GUI from MTRM. It looks like this:

![a](http://image.prntscr.com/image/1e2c2fe42e2d4d06b7c55bd356b2001a.png)

As far I know, NEI has an API that allow you to separate the items when creating GUIs, just like Thermal Expansion does:

![a](http://image.prntscr.com/image/255b66efd75549749b5316666a8fc7ea.png)

**Comment by dries007** [comment]
Yes, but that requires a whole bunch of work I don't have the time for in a new 1.7.10 build if #24 is fixed. Sorry.

Will try and remember for future updates.

**Comment by Claycorp** [comment]
You could also make your GUI smaller or push the keybinding to hide NEI when you don't want it.

**Comment by Eufranio** [comment]
I and the people that I know take the items from NEI so I think it would not be good hiding NEI every time you want to make a new recipe =/

**Comment by Claycorp** [comment]
Spawn in a bunch of items then close it or click the side of the boxes? I used it like this and so did everyone else that used it in 1.7.10. 
Also if I remember correctly parts of the MTRM GUI get cut off on the top and left part because of the "Large" GUI size.

**Comment by dries007** [comment]
Given that the NEI API is a PITA and the GUI side for MTRM is variable depending on what item you put in and which options you select (and that you can avoid this by not playing on a huge GUI scale) its not worth the time I'd have to spend figuring this out.

Current solution is play on GUI scale normal.

**Comment by Eufranio** [comment]
GUI scale Normal:

![a](http://image.prntscr.com/image/1b1b5461fbb141fe860efff744acd274.png)

**Comment by Claycorp** [comment]
Most of the recipe options selections should be outside of the NEI click box for items and there is enough to click the 'OK' and 'Close' buttons for them to work.
You shouldn't need to read them once you see the GUI once.
