### ISSUE TITLE
I can't remove a specific recipe [Solved]

### ISSUE THREAD

**Issue by InterPlay02** [DoubleDoorDevelopment/MineTweakerRecipeMaker#28]
Ok, Hello!

Before we start, I want to tell that I already try to talk with the guys from the mod in question: Embers. Cause I'm trying, first, to remove the original recipe (right?), se then I can change the itens used to make the same item. I already made this with other itens from other mods, and it works! But, when I try to change the recipe for this item, the recipe don't change.
The item is, as it is called, "Tinker's Hammer" (embers:tinker_hammer).
They tell me that this line should work for removing the recipe:
recipes.remove(<embers:tinker_hammer>);

But, when I "/mt reload", the recipe is not removed. Still the same as the original.

**Comment by dries007** [comment]
[You are taling about this recipe right?](https://github.com/RootsTeam/Embers/blob/da3647b7d96c664278706243e38cd03b8ece3411/src/main/java/teamroots/embers/recipe/RecipeRegistry.java#L143-L144)
If that's the case, it should be removable no problem, if it is not, make a manual Minetweaker script and see if that works. If that also doesn't work, its not an issue on our side.

**Comment by InterPlay02** [comment]
No, no... I discovered what is going wrong: The curse app. It don't let me change the mods. So I closed it. Now it works. Sorry for the inconvenience. =)

**Comment by dries007** [comment]
Alright, no problem.
