### ISSUE TITLE
Duplication Glitch?

### ISSUE THREAD

**Issue by InterPlay02** [DoubleDoorDevelopment/MineTweakerRecipeMaker#29]
Ok... Now I really don't know wath is going wrong.
I made this recipe:
![receita](https://cloud.githubusercontent.com/assets/23037423/23633789/dcdc158c-02a5-11e7-937e-ac9bb44abfe1.PNG)

This is the line code:

> `recipes.addShaped(<forestry:crafting_material> * 4, [[<literalascension:iron_carving_tool>.reuse().transformDamage(4), <environmentaltech:ender_stabilized>]]);`

But this is what happens when I try to craft the item:
![feita](https://cloud.githubusercontent.com/assets/23037423/23633831/090204d2-02a6-11e7-9af1-5cce6a455a49.PNG)

If I remove the ".reuse()" part, the item is simply destroyed. Any idea about what should I do?

**Comment by dries007** [comment]
Sorry, but its been far too long. Have you looked on the Minetweaker Wiki? This sort of stuff isn't really related to the GUI (which is the only part we do)

**Comment by Claycorp** [comment]
Again as Dries said This isn't an issue with our mod. You would need to ask on the Minetweaker/CraftTweaker tracker about it.

But that aside according to the wiki you only need the ``.transformDamage()`` to make it take damage. I assume that the ``.reuse()`` is duplicating it as ``.transformDamage()`` should return the item on its own. I have no idea why it wouldn't work without ``.reuse()`` other than the tool doesn't normally take damage?

Wiki Page: http://minetweaker3.powerofbytes.com/wiki/Tutorial:Advanced_Recipes

**Comment by InterPlay02** [comment]
Of course I do. I've been looking at Minetweaker Wiki all day today!

I know people like you don't like to answer the same question over and over. I'm not like the others... Before I make a question related to a problem in this kind of stuff, I always search for a solution by myself. So I always go around, look for a solution and, only after this, I make a question. I already look in to the wiki. But if you don't know how to solve this, ok... I understand.
Where can I find someone to help me?
You know something about a link or whatever that leads me to the Mine Tweaker people?
(Cause in the wiki page, I can't find any link).

**Comment by dries007** [comment]
Most people have an issues link on the CurseForge page too, at the top next to "Files".

Try here: https://github.com/jaredlll08/CraftTweaker/issues
