### ISSUE TITLE
[1.10.2] Mod rejection

### ISSUE THREAD

**Issue by YOYOK9** [DoubleDoorDevelopment/MineTweakerRecipeMaker#33]
I am getting mod rejections when I try to connect to my Vanilla hub. I am using the latest 1.10.2 version 
https://gist.github.com/YOYOK9/47d0e98a2ff6c4090791f6139d2ca9a3

forge-1.10.2-12.18.3.2254-universal
mc: 1.10.2

**Comment by YOYOK9** [comment]
Any news on this?

**Comment by dries007** [comment]
Sorry, I sort of forgot about this, but I can't see why this should happen, because the `acceptableRemoteVersions` is set to `*` which means accept anything, even if it's not there.
You say vanilla hub, do you mean you use a bouncer like BungeeCord?

**Comment by YOYOK9** [comment]
Yes. I am using waterfall which is basically a port of bungee cord. So when I try to connect it fails. It's also a spongeforge server if that helps at all.

**Comment by dries007** [comment]
Ok, I'm afraid you'll have to Bring up this issue with Waterfall. Sponge
shouldn't matter I think.

Op 21 apr. 2017 5:42 a.m. schreef "YOYOK9" <notifications@github.com>:
