### ISSUE TITLE
[Crash] NoMoreRecipeConflict Conflict

### ISSUE THREAD

**Issue by MokahTGS** [DoubleDoorDevelopment/MineTweakerRecipeMaker#34]
This issue still has not been fixed.

https://pastebin.com/Sht33zkZ

Referencing the closed issue #30

**Comment by Claycorp** [comment]
Dries updated the mod fixing the problem the other dev said was causing it. Its his issue now as there is nothing else we can do about it other than take the reload option out or set it to a config option.

**Comment by dries007** [comment]
I'm actually not sure now, but more testing is probably required. Please stop making new issues though, reply to the old one. This is the third issue now, and it's getting annoying to keep track. We can't always reply to a message within a couple of hours.

**Comment by MokahTGS** [comment]
Well one of these needs to be reopened so that we have a place to report issues and test changes.  This issue is still there so it should be labeled "Bug" and open.

**Comment by Claycorp** [comment]
You seem to understand the concept of responding to the issues while they are closed. Just do that.
