### ISSUE TITLE
Suggestion: Adding Support for 9x9 Crafing grid. like Avaritia or Rice Crafting Table

### ISSUE THREAD

**Issue by IDKZAL** [DoubleDoorDevelopment/MineTweakerRecipeMaker#37]
So I think it's really annoying to make a recipe for a 9x9 grid in a text format and I thought why not ask for a GUI version to make life easier. Maybe you could add support to Avaritia Crafting table would be really cool and helpful!

Oh, yea and you should add something like a "cache" to the GUI so it remembers the last items you had in it don't get removed/deleted after you closed it or something like that. 

Regards, IDKZAL

**Comment by dries007** [comment]
This 'issue' has been answered about a million times. The v2 branch of the mod will have support of for _ALL_ types of recipes. The current system can't do it. The v2 branch will be released when it's ready. (It's been in progress for a long time, but I don't have enough time to finish it yet.)

The v1 branche won't have any new features added, so I'll look at the caching for v2, but no promises. At this point I'll be happy if its in a working condition.
