### ISSUE TITLE
Client does not recieve the recipe!

### ISSUE THREAD

**Issue by MineFerdi1** [DoubleDoorDevelopment/MineTweakerRecipeMaker#39]
I made a server with Crafttweaker and the mods i listed below. The problem is whenever a player joins he dont get the the recipe he first must do /mt reload but i have PermissionsEX on the server and i don't know to give a member the permission to do that. The other problem is that i become a huge ERROR message when i do /mt reload (btw i have OP).

Can you say me what the name of the permission is and how to fix the ERROR in the chat? Or please help me to find the problem that players can join and don't "auto" uses  /mt reload

Script: https://pastebin.com/fwLJayDW

1.7.10
Forge Version: 10.13.4.1614
CraftTweaker-1.7.10-3.0.13.jar
and MineTweaker2 is also in the server and client : ModTweaker2-0.9.6.jar

LOG: https://pastebin.com/gCnLeTk3

MODS:
WR-CBE http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/1279956
Waila http://www.curse.com/mc-mods/minecraft/waila
VeinMiner https://minecraft.curseforge.com/projects/veinminer?gameCategorySlug=mc-mods&projectID=67133
AE2Stuff https://minecraft.curseforge.com/projects/ae2-stuff
Tinker's Construct Tooltips http://www.curse.com/mc-mods/minecraft/tic-tooltips
ThermalFoundation http://www.curse.com/mc-mods/minecraft/222880-thermal-foundation
ThermalExpansion http://www.curse.com/mc-mods/minecraft/thermalexpansion
ThermalDynamics http://www.curse.com/mc-mods/minecraft/227443-thermal-dynamics
Tinker's Construct http://www.curse.com/mc-mods/minecraft/tinkers-construct
Simply Jetpacks http://www.curse.com/mc-mods/minecraft/simply-jetpacks
RedstoneArsenal http://www.curse.com/mc-mods/minecraft/redstone-arsenal
Resource Loader https://minecraft.curseforge.com/projects/resource-loader
ProjectRed mods: http://projectredwiki.com/wiki/Main_Page
Patcher https://minecraft.curseforge.com/projects/binniepatcher
Optifine http://www.optifine.net/home
OpenModularTurrets https://minecraft.curseforge.com/projects/openmodularturrets
OpenModsLib http://openmods.info/
OpenBlocks http://openmods.info/
NotEnoughItems http://www.curse.com/mc-mods/minecraft/222211-notenoughitems
NetherOres http://www.curse.com/mc-mods/minecraft/netherores
NEIIntegration http://www.curse.com/mc-mods/minecraft/225251-nei-integration
NEI addons http://www.curse.com/mc-mods/minecraft/nei-addons
ModTweaker2 https://minecraft.curseforge.com/projects/modtweaker?gameCategorySlug=mc-mods&projectID=220954
MineTweakerRecipeMaker https://minecraft.curseforge.com/projects/minetweaker-recipemaker
MineFactoryReloaded https://minecraft.curseforge.com/projects/minefactory-reloaded?gameCategorySlug=mc-mods&projectID=66672
MekansimTools https://mods.curse.com/mc-mods/minecraft/268567-mekanism-tools
MekansimGenerators https://minecraft.curseforge.com/projects/mekanism-generators
Mekanism https://minecraft.curseforge.com/projects/mekanism
Mantle https://minecraft.curseforge.com/projects/mantle?gameCategorySlug=mc-mods&projectID=74924
malisisdoors https://minecraft.curseforge.com/projects/malisisdoors?gameCategorySlug=mc-mods&projectID=223891
malisiscore https://minecraft.curseforge.com/projects/malisiscore
journeymap https://minecraft.curseforge.com/projects/journeymap?gameCategorySlug=mc-mods&projectID=32274
Jabba https://minecraft.curseforge.com/projects/jabba?gameCategorySlug=mc-mods&projectID=73510
ironchest https://minecraft.curseforge.com/projects/ironchests-diamond-chest-returns?gameCategorySlug=customization&projectID=246553
IronBackpacks https://minecraft.curseforge.com/projects/iron-backpacks?gameCategorySlug=mc-mods&projectID=227049
Inventory Tweaks https://minecraft.curseforge.com/projects/inventory-tweaks?gameCategorySlug=mc-mods&projectID=223094
INpureCore https://minecraft.curseforge.com/projects/inpurecore?gameCategorySlug=mc-mods&projectID=223792
iChunUtil https://minecraft.curseforge.com/projects/ichunutil?gameCategorySlug=mc-mods&projectID=229060
Guide API https://minecraft.curseforge.com/projects/guide-api?gameCategorySlug=mc-mods&projectID=228832
FTBUtilities https://minecraft.curseforge.com/projects/ftb-utilities?gameCategorySlug=mc-mods&projectID=237102
FTBTweaks https://minecraft.curseforge.com/projects/ftb-tweaks?gameCategorySlug=mc-mods&projectID=237103
FTBLib https://minecraft.curseforge.com/projects/ftblib?gameCategorySlug=mc-mods&projectID=237167
Flans mod http://www.flansmod.com/
FastLeafDecay https://minecraft.curseforge.com/projects/fast-leaf-decay?gameCategorySlug=mc-mods&projectID=230976
fastcraft https://minecraft.curseforge.com/projects/fastcraft?gameCategorySlug=mc-mods&projectID=242677
extrautilities https://minecraft.curseforge.com/projects/extra-utilities?gameCategorySlug=mc-mods&projectID=225561
ExtraCells https://minecraft.curseforge.com/projects/extra-cells?gameCategorySlug=mc-mods&projectID=63361
EnderTech https://minecraft.curseforge.com/projects/endertech?gameCategorySlug=mc-mods&projectID=223428
EnderStorage https://minecraft.curseforge.com/projects/ender-storage?gameCategorySlug=mc-mods&projectID=229306
EnderIO https://minecraft.curseforge.com/projects/ender-io?gameCategorySlug=mc-mods&projectID=64578
EnderCore https://minecraft.curseforge.com/projects/endercore
denseores https://minecraft.curseforge.com/projects/dense-ores?gameCategorySlug=mc-mods&projectID=224942
DefenseTech https://www.planetminecraft.com/mod/1710-defensetech-v100---missiles-and-high-tech-explosives/
CraftTweaker https://minecraft.curseforge.com/projects/crafttweaker
Custom Main Menu https://mods.curse.com/mc-mods/minecraft/226406-custom-main-menu
ComputerCraft http://www.computercraft.info/
CoFHLib https://minecraft.curseforge.com/projects/cofh-lib?gameCategorySlug=mc-mods&projectID=220333
CoFHCore https://minecraft.curseforge.com/projects/cofhcore?gameCategorySlug=mc-mods&projectID=69162
CodeChickenCore https://minecraft.curseforge.com/projects/codechickencore?gameCategorySlug=mc-mods&projectID=222213
Chisel https://minecraft.curseforge.com/projects/chisel?gameCategorySlug=mc-mods&projectID=235279
ChickenChunks https://mods.curse.com/mc-mods/minecraft/229316-chickenchunks
Carpenter's Blocks https://minecraft.curseforge.com/projects/carpenters-blocks
BigReactors https://minecraft.curseforge.com/projects/big-reactors?gameCategorySlug=mc-mods&projectID=241994
BetterFps https://minecraft.curseforge.com/projects/betterfps
BetterBuildersWands https://minecraft.curseforge.com/projects/better-builders-wands
appliedenergistics2 https://minecraft.curseforge.com/projects/applied-energistics-2?gameCategorySlug=mc-mods&projectID=223794
AOBD https://minecraft.curseforge.com/projects/another-one-bites-the-dust
bspkrsCore https://minecraft.curseforge.com/projects/bspkrscore/files/2227503
Baubles https://minecraft.curseforge.com/projects/baubles?gameCategorySlug=mc-mods&projectID=227083
CodeChickenLib https://minecraft.curseforge.com/projects/codechicken-lib-1-8
common-codec https://commons.apache.org/proper/commons-codec/download_codec.cgi
commons-compress https://commons.apache.org/proper/commons-compress/
ForgeMultipart https://minecraft.curseforge.com/projects/forge-multipart-cbe?gameCategorySlug=mc-mods&projectID=258426
ForgeRelocation https://minecraft.curseforge.com/projects/forge-relocation?gameCategorySlug=mc-mods&projectID=232075
ForgeRelocationFMP https://minecraft.curseforge.com/projects/forge-relocation-fmp-plugin?gameCategorySlug=mc-mods&projectID=232076
MrTJPCore https://minecraft.curseforge.com/projects/mrtjpcore?gameCategorySlug=mc-mods&projectID=229002
Damage Indicators http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/1286538-hit-splat-damage-indicators-v3-3-2-rpg-ui-and
ArmorStatusHUD http://www.minecraftforum.net/topic/1114612-/
StatusEffectHUD http://www.minecraftforum.net/topic/1114612-/

**Comment by dries007** [comment]
PermissionsEX as in the bukkit plugin? You are gonna have a hard time finding any modder who'll accept issue reports with that.

Also: MTRM doesn't have anything to do with this at all, we only create the recipe file, mine/crafttweaker handles everything from there.
