### ISSUE TITLE
Support for BC 6.2.6 Gates?

### ISSUE THREAD

**Issue by Tedyhere** [DoubleDoorDevelopment/MineTweakerRecipeMaker#4]
Could you add support for the different buildcraft gates? I believe they use tags of some sort.  Here is an example.

<BuildCraft|Transport:pipeGate>.withTag({ex: ["buildcraft:pulsar"], mat: 2 as byte, logic: 0 as byte})

Is a Gold AND Gate with a Autarchic Pulsar

Possible? As of now if I put that in a recipe it will use any Gate

**Comment by RenegadeElement** [comment]
what about a search function? where it suggests a tag? Have you seen steves factory manager? A gui in that style would be powerful!!

**Comment by Claycorp** [comment]
NBT tags can't just be looked up. Theres tons of tags that don't get used often thus not included by default on the item. Thus making it impossible to have all the tags that could be used.

Steves factory manager system wouldn't suit this at all. The quantity of options will result in a giant mess. It also doesn't scale well with multiple different setups. The goal some day is to have MineTweaker and ModTweaker support and that system would just make everything overly complex. Its simpler to see what the users sees.

**Comment by dries007** [comment]
Actually, I was thinking of a "steves factory manager"-like approche.
