### ISSUE TITLE
Recipe Maker GUI for Mods?

### ISSUE THREAD

**Issue by InterPlay02** [DoubleDoorDevelopment/MineTweakerRecipeMaker#41]
Hi!

I want to make a suggestion:
What about making a ModTwaker version of the MTRM?
Imagine! If we wnat to add a new AgriCraft Recipe, for example, We just need to open the ModRM and place the recipe. I'm assuming that, if the ModTweaker can edit the recipes of the mods, you can make a GUI to make it more easy for us to edit those recipes.

What do you think about it?

**Comment by dries007** [comment]
See #37 #32 #13 #10 #6 
If I had more time in a day I could finish the v2 branch, which does have support for all of this and more, but I don't unfortunately.
