### ISSUE TITLE
Recipe wont load in game

### ISSUE THREAD

**Issue by iamcarrotmaster** [DoubleDoorDevelopment/MineTweakerRecipeMaker#43]
When i try to make a recipe (or remove one) it will show in the .zs file but wont show up ingame. I've uninstalled and reinstalled the mod and it still doesnt work. Why is this so and how can i fix this please and thank you.

**Comment by iamcarrotmaster** [comment]
it worked at one point

**Comment by Claycorp** [comment]
What version?
Did you restart you game for the recipes to take effect if 1.12+?

**Comment by iamcarrotmaster** [comment]
i am in 1.10.2, sorry meant to mention that

**Comment by iamcarrotmaster** [comment]
and i restarted my game multiple times

**Comment by Claycorp** [comment]
1.10.2 Craft/Minetweaker isn't being worked on anymore, Thus the mod is fine. You either edited the file and broke it or there is an error in your scripts causing them to not load. 

This isn't an issue with the mod itself. Check your logs and your scripts for errors.

**Comment by iamcarrotmaster** [comment]
i did edit it a couple of times manually

**Comment by iamcarrotmaster** [comment]
do you know how to fix it?

**Comment by iamcarrotmaster** [comment]
it did work until then

**Comment by Claycorp** [comment]
That's because whatever you edited was done wrong. There is nothing wrong our mod. If you have issues with CT use http://minetweaker3.powerofbytes.com/wiki/Main_Page to do it correctly. This isn't CT support.

**Comment by iamcarrotmaster** [comment]
sorry
