### ISSUE TITLE
JEI Not Showing Modified Recipes.

### ISSUE THREAD

**Issue by P3rf3ctXZer0** [DoubleDoorDevelopment/MineTweakerRecipeMaker#47]
Not sure why since I have not used this since 1.12 but in the newer 1.12.2 it no longer reflects recipe changes even after server restart

here is the versions I am using
forge-1.12.2-14.23.1.2603-universal.jar

blockdrops-1.12.2-1.4.0.jar
ContentTweaker-1.12.2-4.4.0.jar
CraftTweaker2-1.12-4.1.0.jar
base-1.12.2-3.5.1.jar
jei_1.12.2-4.8.5.147.jar
JustEnoughResources-1.12.2-0.8.6.33.jar
MineTweakerRecipeMaker-1.12.2-1.2.2.30.jar
MTLib-3.0.1.jar
UniDict-1.12.2-2.3.1.jar
WanionLib-1.12.2-1.4.jar

**Comment by dries007** [comment]
You don't actually have crafttweaker installed?

**Comment by P3rf3ctXZer0** [comment]
Oh shit one second I do I thought I posted it. Regardless its starting to look like a JEI issue not a Minetweaker Issue.

**Comment by P3rf3ctXZer0** [comment]
In the mean time place the (Waiting for feedback Label) I will close this issue if it turns out to be something else.

**Comment by dries007** [comment]
Even if it's a Minetweaker issues, we are not minetweaker. This is only the ingame GUI, it does nothing else.
If it turns out to be a Crafttweaker/Minetweaker issue, report it to them.
