### ISSUE TITLE
Removing MW mod recipes not working

### ISSUE THREAD

**Issue by k1r0s** [DoubleDoorDevelopment/MineTweakerRecipeMaker#48]
Tying to remove one recipe to balance a bit with other mods. But seems to ignore my script

script is placed into `mfolder/scripts/ModernWarfare.zs`

```
recipes.removeShaped(
  <mw:Inductor>, 
  [[null, <mw:CopperWiring>, null], 
  [<mw:CopperWiring>, <mw:plastic>, <mw:CopperWiring>],
  [null, <mw:CopperWiring>, null]]
);

```

Im still able to craft this item

![2018-02-24_12 08 14](https://user-images.githubusercontent.com/6052309/36629798-732f42bc-195b-11e8-8be5-a0106528e6d1.png)

any idea about? Thanks

**Comment by dries007** [comment]
This is not Minetweaker/Crafttweaker support.

**Comment by k1r0s** [comment]
Thanks, so its up to mod authors to support this, right?

**Comment by dries007** [comment]
MineTweakerRecipeMaker is not related to MineTweaker or CraftTweaker.
You are not use MineTweakerRecipeMaker. Please go ask somewhere appropriate.
