### ISSUE TITLE
Missing Save button?

### ISSUE THREAD

**Issue by Rsslone** [DoubleDoorDevelopment/MineTweakerRecipeMaker#49]
Not sure how this could have happened but any way I can find out?
https://i.imgur.com/HyGEJWQ.png

**Comment by Claycorp** [comment]
Does the rest of the GUI show up when clicking on any slot option? If not I would assume something is breaking the GUI somehow.

**Comment by Rsslone** [comment]
Indeed it does. Its really weird that only the save button is missing. :thinking:

**Comment by Claycorp** [comment]
All I can think of is to disable mods till it comes back and find out what one is doing it. Other than that perhaps the log will provide some information.

Sorry this isn't much help, we have been idle for some time now.

**Comment by Rsslone** [comment]
Yeah I've already started to remove client side mods to see if that does it. If I find the cause I'll post it here for reference to others.

**Comment by Claycorp** [comment]
Appreciate that, Good luck! Perhaps someday we will be active again!

**Comment by Rsslone** [comment]
I found the issue. It was an out of date version of No Recipe Book mod, this issue was patched 5 days ago. Anyone who has this issue update that mod.

P.S. Your mods are awesome, some of the best server utilities there are, I personally hope you do start up again to update your mods to the new versions.
