### ISSUE TITLE
Need support for NBT data in recipes

### ISSUE THREAD

**Issue by psychofad** [DoubleDoorDevelopment/MineTweakerRecipeMaker#5]
This is a really good mod, but to make it great it really needs to be able to copy any input and output NBT tags into the recipe it creates.  For instance, I am trying to make a recipe that would let you take crystallized essence from Thaumcraft and let you craft an Aspect (consumable for research) from the Thaumcraft NEI plugin.  The recipe is shapeless.  The problem is that the aspect of the crystallized essence is stored in an NBT tag which is not transferred into the recipe maker, so it just treats it as an empty crystallized essence.  I can create this recipe using just Minetweaker and adding the onlyWithTag info into the recipe, so I know this is possible.  It would be awesome if the recipe maker could do all of this for me, however, as there are about 50 aspects and this leads to a LOT of typing.  

This is not the only application of this, just an example.  I also was trying to fix a recipe in ProjectE to only accept fully charged klein stars and ran into this same issue as the stored EMC was saved in an NBT data tag.

This would definitely be a great enhancement to this in-game recipe maker.  Thanks!

**Comment by dries007** [comment]
I know, I know. Its a planned feature, but I need more hours in the day too keep up with school and modding ATM.

**Comment by psychofad** [comment]
Understandable!

**Comment by skittishtrigger** [comment]
Love this mod, made the basic changing/adding sooo easy. Hopefully this "improvement" will be able to be added. In the interim can the nbt data be added manually to the script created by mtrm or does it have to be added directly to a mt3 script?

**Comment by dries007** [comment]
You can manually override the text box at the top of the screen to include whatever things you want, including NBT.

**Comment by skittishtrigger** [comment]
Thank you very much for the response and I hope things are going well for you. /me waves
