### ISSUE TITLE
Question about jei recipes not showing up.

### ISSUE THREAD

**Issue by Adam-R-Kaminski** [DoubleDoorDevelopment/MineTweakerRecipeMaker#50]
Hey there, great mod!
I added a recipe via the gui (with crafttweaker installed), but the recipe doesnt show up in JEI. (yes the recipe works, but doesnt show up )
What am i doing wrong?

**Comment by Claycorp** [comment]
Out of scope.
We don't handle any of the recipe stuff in JEI or how Minetweaker works. Could be an issue with any number of mods but is certainly not us, Sorry.

**Comment by Adam-R-Kaminski** [comment]
Okay, how can i remove recipes though? I can't seem to find any GUI button or WIKI with commands.

**Comment by Claycorp** [comment]
place it in the output slot, check remove and click ok. Otherwise you can put a recipe with the output and hit remove to take only that recipe out.

**Comment by Adam-R-Kaminski** [comment]
Is there any file in the config or somewhere where i can actually read and write down the recipes from? I wasnt able to find that stuff. I just wanted to check what the recipes are.

**Comment by Claycorp** [comment]
Perhaps you should learn how MineTweaker/CraftTweaker works before trying to use this mod.
