### ISSUE TITLE
recpie dont get removed

### ISSUE THREAD

**Issue by voidegg** [DoubleDoorDevelopment/MineTweakerRecipeMaker#51]
i remove a recpie and it still existing. (i re open the world and the changes)

**Comment by Claycorp** [comment]
Do you have MineTweaker or CraftTweaker installed?
What version of minecraft?
Did you read the Giant red text on the project page?

**Comment by voidegg** [comment]
minecraft ver: 1.12.2 
forge ver: 14.23.5.2796
i have crafttweaker installed and i read the giant red text.

**Comment by Claycorp** [comment]
Then you are not following it correctly.

AS OF 1.12+ RELOADING WAS REMOVED YOU MUST RESTART THE GAME/SERVER FOR RECIPES TO TAKE EFFECT! THIS IS NOT A BUG!!!
