### ISSUE TITLE
[Issue with selecting slots] Clicking is too sensitive

### ISSUE THREAD

**Issue by UnlimatedStone9** [DoubleDoorDevelopment/MineTweakerRecipeMaker#52]
I've been dealing with the issue for a long while now, but it's finally gotten to me and bothered me enough to report it, back in older versions of the mod, 1.7.10 to I think 1.10.2 this mod worked wonderfully, however now in more recent versions the clicking of items into the crafting interface is way too finicky, it doesn't always take the item and if I'm trying to use an ore dictionary entry it occasionally won't do that and will instead input the items ID itself

Comparing the current latest version to the version I use in 1.7.10 for my TFC pack the modern version is definitely much too sensitive, which results in those issues described and any time I'm making a recipe, having to close and open the GUI again, resetting the recipe I was working on because of one annoying miss click, I would appreciate it if it was fixed a little so as to not be so annoying and less likely to mess up the recipe

**Comment by Claycorp** [comment]
MTRM is effectively dead, It will not get any updates as there is a replacement that is nearly finished that works far better and should support everything. 
The issue with oredict not taking on click or the not taking the item has always been an issue in all versions. 
As for sensitivity, there is no such thing. It's either the slot is clicked or the slot isn't clicked.

**Comment by Wip-Sama** [comment]
and where can I find this "replacement"

**Comment by Claycorp** [comment]
It was never finished and never released.
