### ISSUE TITLE
Script too large? Unable to load the script.

### ISSUE THREAD

**Issue by Llalpaca** [DoubleDoorDevelopment/MineTweakerRecipeMaker#56]
I know this mod hasn't been updated in a long time, and there is likely practically no chance of a 1.7.10 update, but I was just hoping maybe this is a problem with what I'm doing, and you could shed some light on this. I was working on removing several recipes when the script refused to load and gave me the error "ERROR: Error executing MineTweakerRecipeMaker.zs: Method Code too large!" Is there a script size limit? I've heard of people having thousands of items in their script so I don't think that's an issue with mine? It happened seemingly randomly as well, on a recipe that didn't have very long item names or anything. Here is the file, I'm hoping one of you guys could come back and maybe help me figure out what's going on. I checked around the issues and I couldn't find anything.
[MineTweakerRecipeMaker.zip](https://github.com/DoubleDoorDevelopment/MineTweakerRecipeMaker/files/5527183/MineTweakerRecipeMaker.zip)

**Comment by Claycorp** [comment]
It's not an issue with MTRM and it's not really possible to help without the the logfile from Minetweaker.
