### ISSUE TITLE
Oredict over Itemstack problem

### ISSUE THREAD

**Issue by Wip-Sama** [DoubleDoorDevelopment/MineTweakerRecipeMaker#57]
I started using it because I thought that was faster than cod it myself but every time I need to remove that damn oredict because the mod don't remember what I said I want for the recipe... can you change/implement this feature?

exmple, an item have 2 oredict
-foodAcorn
-foodAcornIron
since I don't wanna the mod to take the first and I don't wanna to switch every time I want the mod to use only **itemStack** but when I remove oredict from a cell if I put an item in another cell or replace the item in that cell the mod start using oredict again... it's quite boring...

it's possible to make possible to chache the option for the session at least?

**Comment by Claycorp** [comment]
Yes, every item placed defaults to oredict as that's the way it's intended. If you don't want it you can easily remove the oredict values with CT.

Sounds like you should just use a loop or something to make recipes instead?
