### ISSUE TITLE
Mending say "Enchanted Book"

### ISSUE THREAD

**Issue by RipMe2Point0** [DoubleDoorDevelopment/MineTweakerRecipeMaker#59]
I am trying to make a Mending recipe but the actual book isn't showing up as "Mending" but instead as "Enchanted Book" in white text. On top of that I don't have a CraftTweaker config and my MineTweaker config is a .zs file. 
![Bug](https://user-images.githubusercontent.com/119878263/222706281-bfb861c6-68e8-484c-8007-0b4ef77dc23f.JPG)
![image](https://user-images.githubusercontent.com/119878263/222706666-1cab77e6-1107-4e8f-8e27-b695ac4c528b.png)

**Comment by Claycorp** [comment]
Helped user in discord, MTRM doesn't support NBT on items, you still need to do anything with NBT manually via script files. Use `/mt hand` to get the data of an item.

**Comment by RipMe2Point0** [comment]
Thanks, if anyone has this same question you need to replace the "enchanted book" recipe with what it copied into your clipboard like this 
![image](https://user-images.githubusercontent.com/119878263/223949855-5fee67f4-558f-4a06-8433-2cf70753195d.png)
also if you can't find the .zs file in configs just search for it in your .minecraft directory type "minetweaker" and it'll come up.
