### ISSUE TITLE
Support for modtweaker ?

### ISSUE THREAD

**Issue by crunkazcanbe** [DoubleDoorDevelopment/MineTweakerRecipeMaker#6]
As the title says .

Thank you

-Crunk

**Comment by Claycorp** [comment]
Someday. More things will be added eventually when time permits. Vanilla is first.

**Comment by crunkazcanbe** [comment]
Cool!

Thank you!

-Crunk

**Comment by 016Nojr** [comment]
I want to bring this up again @Claycorp

**Comment by Claycorp** [comment]
We don't really do much anymore. Anything that is done is mostly stuff that takes less than a day to make, test and OK. I don't foresee much being done with this mod anymore.

**Comment by dries007** [comment]
Its also hardly worth the effort since it can't be done automatically.
