### ISSUE TITLE
Mod Rejection

### ISSUE THREAD

**Issue by Jensran** [DoubleDoorDevelopment/MineTweakerRecipeMaker#7]
I have the latest Mods. Minetweaker Recipe Maker, and Minetweaker, and D3 Core (Tried with and without) and keep getting mod rejection. I'm not sure how to fix this. I've even removed all of the mods and just had it vanilla (with forge) and minetweaker3 and Minetweake recipe maker. 
Crash logs.

http://pastebin.com/Wpinm03a

**Comment by dries007** [comment]
Java Version: 1.6.0_65, Apple Inc.
Update your java, and make sure minecraft is using it to start with.
