### ISSUE TITLE
Needs feedback to the user / documentation on what to expect

### ISSUE THREAD

**Issue by keybounce** [DoubleDoorDevelopment/MineTweakerRecipeMaker#8]
The issue here is simple: There is no feedback to the user about what is going on. There are two OK buttons, with no clue what does what.

I was trying to do something simple. Change a recipe from 5 wood and 3 iron, to 5 wood and 3 gold. I was able to.

But pleas don't ask me which button does what.

I wound up with 2 "remove" lines and 3 "add" lines in the script file.

**Comment by Claycorp** [comment]
Left Ok saves the extra data to the slot * you clicked or edited last. Right Ok saves the edit and reloads the scripts. There really isn't room on the GUI for the information and I don't know for certain if the buttons support tooltips.

**Comment by dries007** [comment]
I only just found out about easy tooltips in guis. This will be added at some point.
