### ISSUE TITLE
Enhancement request: importing original recipe

### ISSUE THREAD

**Issue by Maxwelljones** [DoubleDoorDevelopment/MineTweakerRecipeMaker#9]
Would be great to be able to have a shortcut to import the original recipe.

Thanks for that great and useful mod!

**Comment by Claycorp** [comment]
Sorry for the late reply. Was thinking about how this would work and such.

The idea is great but when it comes to implementing its impossible to do reliably. Items with one recipe would be fine but once they have two what gets imported? What if something is in the oreDictionary? How do you handle that? You can take the first thing from the entry and put it there but that doesn't tell you what else is in that entry.

I don't foresee this being useful unless in very precise circumstances.

**Comment by Maxwelljones** [comment]
I was thinking like how NEI works with crafting tables: Shift-left click
the question mark in a Crafting GUI, and NEI will auto-fill the GUI with
the recipe using whatever items are in your inventory.

I don't know how it would be possible to use that NEI function.

This would sort out the "which entry to choose".

As I'm changing hundreds or recipes, this would save me a lot of time. I
don't know how many people tweak over 250 recipes in a modpack...

Does that help?

**Comment by Claycorp** [comment]
You would need two buttons. Otherwise you would never be able to open one or the other.
It just makes thing more complicated and confusing.

**Comment by Maxwelljones** [comment]
I usually have mtrm open, and then surf NEI, in the same way as I would
when I craft or make recipe for AE2 patterns.
Not sure if you know the shortcut, here's a video showing the use of the
"?" in NEI : https://youtu.be/rQJT-eJONc4?t=57s

As it's not a Crafting GUI, NEI can't auto-fill the recipe when pressing
the "?".

But I understand if this is too much of a hassle on your side. It was
anyway just a thought of something that I thought could be useful instead
of the hassle of always filling my inventory with the craft items (checking
the recipe many times while doing so with the "r" key) and dropping them
into mtrm where maybe this could be done in one click.

Thanks anyway for a nice working mod!

2015-06-12 0:01 GMT+02:00 Claycorp <notifications@github.com>:

**Comment by dries007** [comment]
We work with mods, we know how NEI works :)

It doesn't work because its not a crafting container.
It would probably be a lot of work. But if not, it may be added somewhere in the future.

**Comment by Maxwelljones** [comment]
Sorry if I did underestimate you :=)
I'm coming from the gaming and modpack creating. Modding is for me quite a
dark corner where my knowledge is very small.
Thank you for your explanations!

2015-06-12 0:28 GMT+02:00 Dries007 <notifications@github.com>:

**Comment by dries007** [comment]
No problem, its always better to overexplain then to underexplain something.
